# Data Inspection

### What is Data Inspection?

Data inspection is the process of examining a dataset to understand its structure, contents, data types, distributions, and potential problems before performing data analysis or machine learning.

Real-world example:

A telecom company receives customer data containing:

* Customer ID
* Age
* Contract type
* Monthly charges
* Internet service
* Churn status

Before building a churn prediction model, we need to inspect the data and answer questions such as:

* How many customers are there?
* Which columns are numerical?
* Which are categorical?
* Are there missing values?
* What values occur in each categorical column?

In [1]:
import pandas as pd

df = pd.read_csv("customer_churn.csv")
df.head()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.10,2394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.50,3796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

### 1. Number of Rows

The number of rows represents the number of records or observations in the dataset.

In this dataset, each row represents one customer record.

Real-world example:

If a telecom company has information about 5,020 customers, there will be 5,020 rows.

#### AI/ML usage

The number of observations affects:

* Model training
* Model accuracy
* Statistical reliability
* Train/test splitting

More useful observations generally give an ML model more information to learn from.

In [2]:
print("Number of rows:", len(df))

Number of rows: 5020

### 2. Number of Columns

The number of columns represents the number of variables or attributes in the dataset.

Real-world example:

For a customer, we have information such as:

* Age
* Gender
* Monthly charges
* Contract type
* Internet service
* Churn

Each of these is represented by a column.

#### AI/ML usage

Columns usually become features used by an ML model.

In [3]:
print("Number of columns:", len(df.columns))

Number of columns: 14

In [4]:
print(df.columns)

Index(['CustomerID', 'Age', 'Gender', 'TenureYears', 'MonthlyCharges',
       'TotalCharges', 'ContractType', 'InternetService', 'PaymentMethod',
       'SeniorCitizen', 'SupportCalls', 'StreamingService', 'PaperlessBilling',
       'Churn'],
      dtype='str')

### 3. DataTypes

A data type tells us what kind of data is stored in a column.

Common types include:

| Data Type  | Meaning                       | Example      |
| ---------- | ----------------------------- | ------------ |
| `int64`    | Integer                       | 5, 10, 20    |
| `float64`  | Decimal number                | 25.5, 100.75 |
| `object`   | Usually text/categorical data | Male, Female |
| `datetime` | Date/time                     | 2026-08-14   |

#### AI/ML usage

Data types determine what preprocessing is required.

In [5]:
df.dtypes

CustomerID              str
Age                 float64
Gender                  str
TenureYears           int64
MonthlyCharges      float64
TotalCharges        float64
ContractType            str
InternetService         str
PaymentMethod           str
SeniorCitizen           str
SupportCalls          int64
StreamingService        str
PaperlessBilling        str
Churn                   str
dtype: object

### 4. Index

An index is used to identify the position of each row in a Pandas DataFrame.

By default, Pandas creates a numerical index starting from 0.

Real-world example:

The index can be thought of as the row number:

Index     CustomerID

0         CUST00001

1         CUST00002

2         CUST00003

#### AI/ML usage

The index normally isn't used as an ML feature.

For example, this:

0, 1, 2, 3, 4...doesn't contain meaningful information about customer churn.

In [6]:
print(df.index)

RangeIndex(start=0, stop=5020, step=1)

In [7]:
# We can inspect the first few index values

print(df.index[:10])

RangeIndex(start=0, stop=10, step=1)

In [8]:
# We can also access one row using its index

print(df.loc[0])

CustomerID              CUST00001
Age                          56.0
Gender                     Female
TenureYears                     0
MonthlyCharges              20.41
TotalCharges               131.92
ContractType             One year
InternetService               DSL
PaymentMethod       Bank transfer
SeniorCitizen                  No
SupportCalls                    3
StreamingService               No
PaperlessBilling              Yes
Churn                         Yes
Name: 0, dtype: object

### 5. head()

The head() method displays the first five rows by default.

Why use it?

It helps us quickly understand:

* Column names
* Sample values
* Data structure
* Whether the data loaded correctly

Real-world usage:

If you have thousands of customer records, you don't want to print everything.

Instead, head() lets you quickly inspect the beginning of the dataset.

#### AI/ML usage

Useful for:

* Checking whether data loaded correctly
* Checking column names
* Checking sample values
* Detecting obvious formatting problems

In [9]:
df.head()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.10,2394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.50,3796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

In [10]:
df.head(10)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.10,2394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.50,3796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes
5,CUST00006,25.0,Male,5,90.88,5818.04,Two year,DSL,Mailed check,No,0,No,No,No
6,CUST00007,38.0,Female,5,37.79,2670.55,Month-to-month,DSL,Mailed check,No,1,Yes,Yes,No
7,CUST00008,56.0,Male,0,108.85,1106.71,Two year,No,Electronic check,No,4,Yes,No,Yes
8,CUST00009,36.0,Male,9,64.19,7652.76,One year,DSL,Mailed check,No,3,Yes,No,No
9,CUST00010,40.0,Male,1,34.28,618.59,One year,Fiber optic,Electronic check,No,3,Yes,Yes,No

### 6. tail()

The tail() method displays the last five rows.

Why use it?

It can help check whether:

* The file was loaded completely
* The final records look correct
* There are unusual values at the end of the dataset

In [11]:
df.tail()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
5015,CUST00616,49.0,Male,6,32.29,2588.15,One year,DSL,Mailed check,No,3,No,Yes,Yes
5016,CUST00641,36.0,Female,9,71.92,8511.32,Month-to-month,No,Bank transfer,No,5,No,Yes,No
5017,CUST03709,66.0,Male,2,34.41,1200.43,Two year,Fiber optic,Credit card,Yes,1,Yes,No,No
5018,CUST02367,63.0,Male,6,111.09,8967.34,Two year,DSL,Electronic check,Yes,1,No,Yes,No
5019,CUST02756,29.0,Male,8,28.23,3021.45,One year,Fiber optic,Credit card,No,0,Yes,Yes,No

In [12]:
df.tail(10)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
5010,CUST04393,24.0,Male,5,84.63,6005.95,Two year,No,Mailed check,No,0,Yes,Yes,No
5011,CUST03485,43.0,Male,10,117.65,15278.80,One year,Fiber optic,Credit card,No,0,Yes,No,Yes
5012,CUST02962,53.0,Female,6,85.98,NaN,Month-to-month,No,Credit card,No,4,Yes,No,Yes
5013,CUST03216,67.0,Male,2,62.74,2202.74,One year,Fiber optic,Bank transfer,Yes,2,No,Yes,No
5014,CUST04302,55.0,Male,9,21.57,2367.15,Month-to-month,No,Bank transfer,No,2,Yes,No,No
5015,CUST00616,49.0,Male,6,32.29,2588.15,One year,DSL,Mailed check,No,3,No,Yes,Yes
5016,CUST00641,36.0,Female,9,71.92,8511.32,Month-to-month,No,Bank transfer,No,5,No,Yes,No
5017,CUST03709,66.0,Male,2,34.41,1200.43,Two year,Fiber optic,Credit card,Yes,1,Yes,No,No
5018,CUST02367,63.0,Male,6,111.09,8967.34,Two year,DSL,Electronic check,Yes,1,No,Yes,No
5019,CUST02756,29.0,Male,8,28.23,3021.45,One year,Fiber optic,Credit card,No,0,Yes,Yes,No

### 7. sample()

sample() randomly selects rows from a DataFrame.

#### AI/ML usage

Random samples are useful for:

Quickly inspecting a dataset
Checking whether data is representative
Detecting unusual values
Understanding different observations

In [13]:
df.sample()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
3373,CUST03374,56.0,Female,3,41.13,1889.23,Month-to-month,Fiber optic,Credit card,No,2,No,No,No

In [14]:
# Get 5 random rows:

df.sample(5)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
3592,CUST03593,50.0,Male,3,62.25,2449.20,Month-to-month,Fiber optic,Credit card,No,1,No,No,Yes
1952,CUST01953,19.0,Male,2,108.17,3339.94,Two year,No,Mailed check,No,1,No,Yes,No
737,CUST00738,49.0,Female,4,103.30,5432.94,Month-to-month,DSL,Credit card,No,2,No,Yes,No
1561,CUST01562,34.0,Female,9,98.45,11623.20,Month-to-month,No,Bank transfer,No,0,No,Yes,No
412,CUST00413,19.0,Female,10,77.16,9993.77,Two year,Fiber optic,Mailed check,No,2,Yes,Yes,No

In [15]:
# For reproducible results: With random_state=42 we get the same random sample each time.

df.sample(5, random_state=42)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
1504,CUST01505,55.0,Female,7,64.28,5769.97,One year,DSL,Bank transfer,No,0,Yes,Yes,No
538,CUST00539,69.0,Female,6,64.56,5173.33,Month-to-month,Fiber optic,Mailed check,Yes,1,No,Yes,No
3551,CUST03552,31.0,Male,10,65.59,8207.14,Month-to-month,Fiber optic,Credit card,No,3,No,No,No
4945,CUST04946,55.0,Male,10,37.23,4708.47,Month-to-month,DSL,Bank transfer,No,1,No,Yes,No
4817,CUST04818,31.0,Female,9,32.18,3694.32,Two year,No,Credit card,No,3,Yes,Yes,Yes

### 8. shape

shape returns the dimensions of a DataFrame.

It returns:

(rows, columns)

#### AI/ML usage

shape is useful for checking the size of your dataset before and after preprocessing.

In [16]:
print(df.shape)

(5020, 14)

This means:

5020 rows

14 columns

### 9. info()

info() provides a summary of the DataFrame, including:

* Number of rows
* Column names
* Non-null values
* Data types
* Memory usage

Why is it important?

It gives us a quick overview of the entire dataset.

For example, we can identify:

Age              float64

TenureYears       int64

Gender            object

MonthlyCharges   float64

It also helps identify columns with missing values.

#### AI/ML usage

Before training an ML model, we need to know:

* Which columns contain missing values?
* Which columns are numerical?
* Which are categorical?
* Are the data types appropriate?

info() helps answer these questions quickly.

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5020 entries, 0 to 5019
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        5020 non-null   str
 1   Age               4969 non-null   float64
 2   Gender            5020 non-null   str
 3   TenureYears       5020 non-null   int64
 4   MonthlyCharges    4970 non-null   float64
 5   TotalCharges      4969 non-null   float64
 6   ContractType      5020 non-null   str
 7   InternetService   5020 non-null   str
 8   PaymentMethod     5020 non-null   str
 9   SeniorCitizen     5020 non-null   str
 10  SupportCalls      5020 non-null   int64
 11  StreamingService  5020 non-null   str
 12  PaperlessBilling  5020 non-null   str
 13  Churn             5020 non-null   str
dtypes: float64(3), int64(2), str(9)
memory usage: 814.5 KB

### 10. describe()

describe() provides statistical summaries of numerical columns.

It typically gives:

| Statistic | Meaning                   |
| --------- | ------------------------- |
| count     | Number of non-null values |
| mean      | Average                   |
| std       | Standard deviation        |
| min       | Minimum                   |
| 25%       | First quartile            |
| 50%       | Median                    |
| 75%       | Third quartile            |
| max       | Maximum                   |

In [18]:
df.describe()

               Age  TenureYears  MonthlyCharges  TotalCharges  SupportCalls
count  4969.000000  5020.000000     4970.000000   4969.000000   5020.000000
mean     43.580600     5.043426       70.085469   4679.134800      1.988048
std      14.922491     3.162546       28.852719   3468.389578      1.416837
min      18.000000     0.000000       20.020000     29.350000      0.000000
25%      31.000000     2.000000       45.920000   1883.140000      1.000000
50%      43.000000     5.000000       70.165000   3830.980000      2.000000
75%      56.000000     8.000000       94.957500   6917.120000      3.000000
max      69.000000    10.000000      119.980000  15559.290000      9.000000

Example:

Suppose, Age

mean = 45

min = 18

max = 80

This tells us the average customer age is around 45.

#### AI/ML usage

describe() helps detect:

* Outliers
* Unexpected values
* Large differences in scale
* Distribution characteristics

### 11. dtypes

dtypes returns the data type of every column.

#### AI/ML usage

It helps determine which preprocessing technique should be applied.

For example:

* float64 → numerical processing
* int64   → numerical processing
* object  → categorical processing

In [19]:
df.dtypes

CustomerID              str
Age                 float64
Gender                  str
TenureYears           int64
MonthlyCharges      float64
TotalCharges        float64
ContractType            str
InternetService         str
PaymentMethod           str
SeniorCitizen           str
SupportCalls          int64
StreamingService        str
PaperlessBilling        str
Churn                   str
dtype: object

### 12. nunique()

nunique() returns the number of unique values in each column.

#### AI/ML usage

It helps identify:

* Categorical variables
* High-cardinality columns
* Identifier columns

For example, if:

CustomerID → 5020 unique values

and there are 5,020 rows, it is likely an identifier rather than a useful predictive feature.

In [20]:
print(df.nunique())

CustomerID          5000
Age                   52
Gender                 3
TenureYears           11
MonthlyCharges      3921
TotalCharges        4938
ContractType           4
InternetService        4
PaymentMethod          4
SeniorCitizen          2
SupportCalls          10
StreamingService       2
PaperlessBilling       2
Churn                  2
dtype: int64

### 13. value_counts()

value_counts() is a Pandas function used to count how many times each unique value appears in a column.

It is mainly useful for understanding the distribution of categorical data.

Example:

Suppose a telecom company has:

| Contract Type | Customers |
| ------------- | --------: |
| Monthly       |     2,500 |
| Yearly        |     1,500 |
| Two Year      |     1,020 |

This tells the company how many customers have each type of contract.

#### AI/ML usage

value_counts() is useful during Exploratory Data Analysis (EDA) to:

* Understand categorical distributions
* Identify class imbalance
* Check target variable distribution
* Find rare categories
* Detect unexpected values

In [21]:
# For Gender:

df["Gender"].value_counts()

Gender
Female    2521
Male      2498
female       1
Name: count, dtype: int64

In [22]:
# For Churn:

df["Churn"].value_counts()

Churn
No     3623
Yes    1397
Name: count, dtype: int64

### 14.Numerical Columns

Numerical columns contain values that represent numbers and on which mathematical operations can be performed.

Examples:

* Age
* Salary
* Price
* Temperature
* Number of transactions

Numerical variables can generally be:

Discrete → countable values

Continuous → measurable values

Real-world example

In a telecom company:

* Age → numerical
* Monthly charges → numerical
* Number of support calls → numerical
* Years as a customer → numerical

#### AI/ML usage

Numerical features are extremely important in ML models.

They can be used for:

* Prediction
* Classification
* Regression
* Clustering
* Statistical analysis

Some ML algorithms, such as Logistic Regression, KNN and SVM, may require feature scaling.

In [23]:
numerical_columns = df.select_dtypes(include="number").columns

print(numerical_columns)

Index(['Age', 'TenureYears', 'MonthlyCharges', 'TotalCharges', 'SupportCalls'], dtype='str')

### 15. Categorical Columns

Categorical columns contain values representing categories or groups rather than continuous numerical measurements.

Examples:

* Gender
* City
* Payment method
* Contract type
* Yes/No values

Example:

For telecom customers:

Gender : Male, Female

These represent categories.

#### AI/ML usage

Most ML algorithms require numerical input, so categorical variables often need to be converted into numbers.

Common techniques:

* Label Encoding
* One-Hot Encoding
* Ordinal Encoding

For example:

Gender

Male   → 1
Female → 0

In [25]:
categorical_columns = df.select_dtypes(include="str").columns

print(categorical_columns)

Index(['CustomerID', 'Gender', 'ContractType', 'InternetService',
       'PaymentMethod', 'SeniorCitizen', 'StreamingService',
       'PaperlessBilling', 'Churn'],
      dtype='str')

### 16. Date/Time Columns

A date/time column contains information about dates or timestamps.

Examples:

2026-08-16

2025-01-15 10:30:00

Date/time information can be used to extract:

* Year
* Month
* Day
* Day of week
* Hour
* Duration

Example:

An e-commerce company might have:

PurchaseDate

From this, we could determine:

-> Which month has the most sales?

-> Which day has the highest number of orders?

-> How long has a customer been inactive?

#### AI/ML usage

Date/time variables can be converted into useful features such as:

* Year
* Month
* Day
* DayOfWeek
* DaysSinceLastPurchase

These features can improve ML models.

In [26]:
df.dtypes

CustomerID              str
Age                 float64
Gender                  str
TenureYears           int64
MonthlyCharges      float64
TotalCharges        float64
ContractType            str
InternetService         str
PaymentMethod           str
SeniorCitizen           str
SupportCalls          int64
StreamingService        str
PaperlessBilling        str
Churn                   str
dtype: object

In [28]:
df["TenureGroup"] = pd.cut(
    df["TenureYears"],
    bins=[0, 2, 5, 10, float("inf")],
    labels=["0-2 Years", "3-5 Years", "6-10 Years", "10+ Years"]
)

df["TenureGroup"]

0              NaN
1       6-10 Years
2        3-5 Years
3       6-10 Years
4       6-10 Years
           ...
5015    6-10 Years
5016    6-10 Years
5017     0-2 Years
5018    6-10 Years
5019    6-10 Years
Name: TenureGroup, Length: 5020, dtype: category
Categories (4, str): ['0-2 Years' < '3-5 Years' < '6-10 Years' < '10+ Years']

### 17. Identifier Columns

An identifier column uniquely identifies each record or entity.

Examples:

* CustomerID
* EmployeeID
* OrderID
* TransactionID

An identifier is generally not a meaningful predictive feature.

Example:

A bank might have:

CustomerID = CUST001

CustomerID = CUST002

CustomerID = CUST003

The ID identifies the customer but doesn't describe their behavior.

#### AI/ML usage

Identifiers are generally excluded from ML models because they don't provide meaningful information.

Including them can:

* Add noise
* Cause overfitting
* Create misleading patterns
* Reduce model generalization

In [29]:
df["CustomerID"].head()

0    CUST00001
1    CUST00002
2    CUST00003
3    CUST00004
4    CUST00005
Name: CustomerID, dtype: str

### 18. Potential Target Columns

The target variable is the variable that we want our ML model to predict.

It is also called:

* Dependent variable
* Output variable
* Response variable
* Label

Example:

If a company wants to predict whether a customer will leave:

Churn is the target.

If Churn = Yes -> the customer left.

If Churn = No -> the customer stayed.

#### AI/ML usage

The target variable is represented as y in supervised learning.

Features are represented as X.

X → Customer information

y → Churn

In [30]:
df["Churn"].value_counts()

Churn
No     3623
Yes    1397
Name: count, dtype: int64